[functions.mcp]
import_map = "functions/mcp/deno.json"
verify_jwt = false

[functions.daily-aggregates]
import_map = "functions/deno.json"
verify_jwt = false

# Configures S3 bucket URL, eg. <bucket_name>.s3-<region>.amazonaws.com
s3_host = "env(S3_HOST)"
# Configures S3 bucket region, eg. us-east-1
s3_region = "env(S3_REGION)"
# Configures S3 bucket access key, eg. FAKEACCESSKEY (only in dev)
s3_access_key = "env(S3_ACCESS_KEY)"
# Configures S3 bucket secret key, eg. FAKESECRETKEY (only in dev)
s3_secret_key = "env(S3_SECRET_KEY)"

