-- Update agent_outputs RLS to allow clinic-wide visibility for authenticated users.
-- This ensures that reports generated by background workflows (via REPORT_USER_ID)
-- are visible to all members of the same clinic.

-- 1) Backfill clinic_id for existing agent_outputs where missing
UPDATE public.agent_outputs ao
SET clinic_id = u.clinic_id
FROM public.users u
WHERE ao.user_id = u.id
  AND ao.clinic_id IS NULL;

-- 2) Update RLS policies
DROP POLICY IF EXISTS agent_outputs_select_own ON public.agent_outputs;
DROP POLICY IF EXISTS agent_outputs_select_clinic ON public.agent_outputs;

CREATE POLICY agent_outputs_select_clinic
  ON public.agent_outputs
  FOR SELECT
  TO authenticated
  USING (
    auth.uid() = user_id OR
    clinic_id = ((auth.jwt() ->> 'clinic_id'::text))::uuid
  );
