-- Doctoralia channel reporting views were repaired in production.
-- Production migration applied:
-- recreate_doctoralia_channel_views_with_patient_names
--
-- Fix:
-- - v_new_clients_by_channel_detail resolves client_name from patient_name,
--   template_patient_name, patient_phone and fallback.
-- - identity_key uses phone_normalized, patient_phone, DNI, patient_name,
--   template_patient_name and id.
-- - v_new_clients_by_channel_monthly was recreated preserving user_id and clinic_id.
--
-- No-op migration kept to align repository history.
select 1;
