-- 20260504203000_doctoralia_lead_traceability_unified_view.sql
-- Historical placeholder kept for migration ordering compatibility.
-- Canonical definition of public.vw_doctoralia_lead_traceability_unified
-- lives in:
--   20260514084000_unify_appointment_source_of_truth.sql
-- to avoid drift from duplicated view bodies.
