ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS first_outbound_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS first_inbound_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reply_delay_minutes NUMERIC,
  ADD COLUMN IF NOT EXISTS lost_reason TEXT,
  ADD COLUMN IF NOT EXISTS dni_hash TEXT,
  ADD COLUMN IF NOT EXISTS dni TEXT;
