-- =============================================================================
-- Doctoralia raw ingestion foundation
--
-- Some historical environments had public.doctoralia_raw created manually/remotely.
-- Clean database rebuilds need the table before later Doctoralia migrations create
-- views and add parsed columns that reference it.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.doctoralia_raw (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id    UUID REFERENCES public.clinics(id) ON DELETE CASCADE,
  upload_id    UUID,
  raw_row      JSONB NOT NULL DEFAULT '{}'::jsonb,
  processed    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.doctoralia_raw
  ADD COLUMN IF NOT EXISTS clinic_id  UUID REFERENCES public.clinics(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS upload_id  UUID,
  ADD COLUMN IF NOT EXISTS raw_row    JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS processed  BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

CREATE INDEX IF NOT EXISTS doctoralia_raw_clinic_id_idx
  ON public.doctoralia_raw(clinic_id);

CREATE INDEX IF NOT EXISTS doctoralia_raw_upload_id_idx
  ON public.doctoralia_raw(upload_id)
  WHERE upload_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS doctoralia_raw_unprocessed_idx
  ON public.doctoralia_raw(clinic_id, created_at DESC)
  WHERE processed = FALSE;

ALTER TABLE public.doctoralia_raw ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS doctoralia_raw_service_role ON public.doctoralia_raw;
CREATE POLICY doctoralia_raw_service_role
  ON public.doctoralia_raw
  FOR ALL
  TO service_role
  USING (TRUE)
  WITH CHECK (TRUE);
