-- =============================================================================
-- Ensure Doctoralia raw table supports Produccion Intermediarios KPI views
--
-- The 20260504180000 migration creates views that read public.doctoralia_raw and
-- expect these parsed columns to exist. Some preview/drifted environments had
-- doctoralia_raw without the parsed columns because earlier remote-only setup or
-- guarded migrations did not add them. This migration must run immediately before
-- 20260504180000 so the historical view migration can compile.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.doctoralia_raw (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clinic_id    UUID REFERENCES public.clinics(id) ON DELETE CASCADE,
  upload_id    UUID,
  raw_row      JSONB NOT NULL DEFAULT '{}'::jsonb,
  processed    BOOLEAN NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.doctoralia_raw
  ADD COLUMN IF NOT EXISTS clinic_id       UUID REFERENCES public.clinics(id) ON DELETE CASCADE,
  ADD COLUMN IF NOT EXISTS upload_id       UUID,
  ADD COLUMN IF NOT EXISTS raw_row         JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS processed       BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS estado          VARCHAR(32),
  ADD COLUMN IF NOT EXISTS importe         NUMERIC(12,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fecha           DATE,
  ADD COLUMN IF NOT EXISTS fecha_creacion  DATE,
  ADD COLUMN IF NOT EXISTS agenda          VARCHAR(128),
  ADD COLUMN IF NOT EXISTS treatment       TEXT;

CREATE INDEX IF NOT EXISTS doctoralia_raw_clinic_id_idx
  ON public.doctoralia_raw(clinic_id);

CREATE INDEX IF NOT EXISTS doctoralia_raw_intermediarios_kpis_idx
  ON public.doctoralia_raw(clinic_id, fecha, estado)
  WHERE fecha IS NOT NULL;

ALTER TABLE public.doctoralia_raw ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS doctoralia_raw_service_role ON public.doctoralia_raw;
CREATE POLICY doctoralia_raw_service_role
  ON public.doctoralia_raw
  FOR ALL
  TO service_role
  USING (TRUE)
  WITH CHECK (TRUE);
