-- Canonical SEO web-performance telemetry.
-- Source: Google PageSpeed Insights API v5 (Lighthouse lab data + opportunistic CrUX INP).

CREATE TABLE IF NOT EXISTS public.seo_web_performance (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id uuid NOT NULL,
  url text NOT NULL,
  device text NOT NULL CHECK (device IN ('mobile', 'desktop')),
  source text NOT NULL DEFAULT 'pagespeed_insights_v5',
  performance_score smallint CHECK (performance_score IS NULL OR performance_score BETWEEN 0 AND 100),
  lcp_ms integer CHECK (lcp_ms IS NULL OR lcp_ms >= 0),
  cls numeric(10, 4) CHECK (cls IS NULL OR cls >= 0),
  inp_ms integer CHECK (inp_ms IS NULL OR inp_ms >= 0),
  fcp_ms integer CHECK (fcp_ms IS NULL OR fcp_ms >= 0),
  tbt_ms integer CHECK (tbt_ms IS NULL OR tbt_ms >= 0),
  speed_index_ms integer CHECK (speed_index_ms IS NULL OR speed_index_ms >= 0),
  ttfb_ms integer CHECK (ttfb_ms IS NULL OR ttfb_ms >= 0),
  field_scope text CHECK (field_scope IS NULL OR field_scope IN ('url', 'origin')),
  quality_status text NOT NULL CHECK (quality_status IN ('ok', 'partial', 'unavailable')),
  error_code text,
  error_message text,
  provider_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  captured_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT seo_web_performance_url_https CHECK (url ~ '^https://nuvanx[.]com(/|$)'),
  CONSTRAINT seo_web_performance_error_contract CHECK (
    (quality_status = 'unavailable' AND error_code IS NOT NULL)
    OR (quality_status <> 'unavailable' AND error_code IS NULL)
  ),
  CONSTRAINT seo_web_performance_run_cell_unique UNIQUE (run_id, url, device)
);

CREATE INDEX IF NOT EXISTS seo_web_performance_latest_cell_idx
  ON public.seo_web_performance (url, device, captured_at DESC);

CREATE INDEX IF NOT EXISTS seo_web_performance_latest_run_idx
  ON public.seo_web_performance (captured_at DESC, run_id);

ALTER TABLE public.seo_web_performance ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.seo_web_performance FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.seo_web_performance TO authenticated;
GRANT ALL ON TABLE public.seo_web_performance TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.seo_web_performance_id_seq TO service_role;

DROP POLICY IF EXISTS seo_web_performance_service_role_all ON public.seo_web_performance;
CREATE POLICY seo_web_performance_service_role_all
  ON public.seo_web_performance
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS seo_web_performance_authenticated_select ON public.seo_web_performance;
CREATE POLICY seo_web_performance_authenticated_select
  ON public.seo_web_performance
  FOR SELECT
  TO authenticated
  USING ((SELECT auth.jwt() ->> 'is_anonymous') IS DISTINCT FROM 'true');

COMMENT ON TABLE public.seo_web_performance IS
  'Canonical PageSpeed/Lighthouse snapshots for the NUVANX production site. Failed provider cells are persisted as unavailable instead of backfilled with estimates.';

COMMENT ON COLUMN public.seo_web_performance.inp_ms IS
  'CrUX INP percentile when exposed by PageSpeed for the exact URL, otherwise origin fallback with field_scope=origin; nullable when field data is unavailable.';

CREATE OR REPLACE FUNCTION public.nvx_dispatch_seo_web_performance()
RETURNS bigint
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_secret text;
  v_project_url text;
  v_request_id bigint;
BEGIN
  SELECT trim(decrypted_secret) INTO v_secret
  FROM vault.decrypted_secrets
  WHERE name = 'REVOPS_INTERNAL_SECRET'
  LIMIT 1;

  IF v_secret IS NULL OR length(v_secret) < 32 THEN
    RAISE EXCEPTION 'SEO telemetry internal credential unavailable';
  END IF;

  SELECT trim(decrypted_secret) INTO v_project_url
  FROM vault.decrypted_secrets
  WHERE name = 'REVOPS_PROJECT_URL'
  LIMIT 1;

  IF v_project_url IS NULL OR v_project_url !~ '^https://[a-z0-9-]+[.]supabase[.]co$' THEN
    RAISE EXCEPTION 'SEO telemetry project URL unavailable';
  END IF;

  SELECT net.http_post(
    url := v_project_url || '/functions/v1/seo-web-performance',
    headers := pg_catalog.jsonb_build_object(
      'Content-Type', 'application/json',
      'x-nvx-internal-secret', v_secret
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 5000
  ) INTO v_request_id;

  RETURN v_request_id;
END;
$$;

REVOKE ALL ON FUNCTION public.nvx_dispatch_seo_web_performance() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.nvx_dispatch_seo_web_performance() TO service_role;

DO $$
DECLARE
  target_job record;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron') THEN
    RAISE EXCEPTION 'pg_cron is required for SEO telemetry scheduling';
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_net') THEN
    RAISE EXCEPTION 'pg_net is required for SEO telemetry dispatch';
  END IF;

  FOR target_job IN
    SELECT jobid
    FROM cron.job
    WHERE jobname = 'nvx-seo-web-performance-daily'
  LOOP
    PERFORM cron.unschedule(target_job.jobid);
  END LOOP;

  PERFORM cron.schedule(
    'nvx-seo-web-performance-daily',
    '25 5 * * *',
    $cron$SELECT public.nvx_dispatch_seo_web_performance();$cron$
  );
END;
$$;
